#!/bin/bash
# Python Application
# Generated by agent-harness

set -e

# Check for virtual environment
if [ ! -d "venv" ]; then
    echo "Creating virtual environment..."
    python -m venv venv
fi

# Activate venv
source venv/bin/activate

# Install dependencies
if [ -f "requirements.txt" ]; then
    pip install -r requirements.txt -q
elif [ -f "pyproject.toml" ]; then
    pip install -e . -q
fi

echo "Python environment ready"
echo "Run your application manually"
